/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 */

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;


public class HibernateDemo {

    public static void testGet() {
        Session session = null;
        Transaction tx = null;

        try {
            //与本地线程绑定的session
            session = HibernateUtils.getSessionObject();
            //开启事务
            tx = session.beginTransaction();
            
            //根据uid =2查询
            User user = session.get(User.class, 2);//23行
            user.setUsername("hanser");
            System.out.println("----------------------");
            
            session.save(user);
            //int i = 10/0;
            tx.commit();

        } catch(Exception e) {
            e.printStackTrace();
            //回滚事务
            tx.rollback();
        } finally {
            session.close();
        }

    }

    public static void main(String args[]) {
        testGet();
    }
}
