/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * 持久态更新数据库(磁盘)
 */

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;


public class HibernateDemo {

    public static void testGet() {
        SessionFactory sessionFactory = HibernateUtils.getSessionFactory();

        Session session = sessionFactory.openSession();

        Transaction tx = session.beginTransaction();
        //根据uid =2查询
        User user = session.get(User.class, 2);//23行
        user.setUsername("hanser");
        System.out.println("----------------------");
        
        tx.commit();

        session.close();
        sessionFactory.close();
    }

    public static void main(String args[]) {
        testGet();
    }
}
